### ISSUE TITLE
finding gRNAs on a single gene

### ISSUE THREAD

**Issue by batflorez** [zhangchonglab/CRISPRi-functional-genomics-in-prokaryotes#2]
[config_mApple2_gRNA_100919.txt](https://github.com/zhangchonglab/CRISPRi-functional-genomics-in-prokaryotes/files/3714579/config_mApple2_gRNA_100919.txt)
first of all, nice tool!. I have been trying to use it to automatically design gRNAs for my experiments (I am not running libraries at the moment). I'm doing a control experiment where I want to find gRNAs for a fluorescent protein (mApple2) so that would be just one gene (see attached). I had to modify the code a bit because I am using python 3, however the analysis runs well but I get the following error:

Design process for mApple2 starts.
Copy number: 1
Gene length: 711.0
Command line:./seqmap 5 N20NGGofftarget.fasta NC_022898_PY79.fna seqmapOut.temp.dat /output_all_matches 
Loading fasta file N20NGGofftarget.fasta.
56 sequences read, total length is 1288.
analysing probes...totally 56 probes, minimum length = 23, maximum length = 23, set internal key length = 23
importing probes....56 probes imported. 56 are valid.
checking resources...64-bit version.
available memory: 8128MB.
generating reversed probes for searching reverse strand
now 112 probes. 112 are valid.
Split probe into 6 parts.
total 6 copies of probes.
estimated memory usage: 12MB.
Building 6 probe lists......6 probe lists created.
estimated search speed is 302118 bps/sec.
detecting probes
....
average search steps:1.08999 maximum search steps:4
4033459 base pairs processed. average search speed: 694514 bps/sec.
time used: 17.6061 seconds
4 sgRNA detected for mApple2

cut: mApple2_mNeon.gene_statistics.txt: No such file or directory
cut: mApple2_mNeon.sgRNA_statistics.txt: No such file or directory
Traceback (most recent call last):
  File "sgRNA_desgin_main.py", line 348, in <module>
    main(sys.argv[1])
  File "sgRNA_desgin_main.py", line 329, in main
    processSgRNASequence('%s.N20.fasta.txt'%(varlist['prefix']),'N20_library.csv','w',False)
  File "sgRNA_desgin_main.py", line 265, in processSgRNASequence
    with open(N20file,'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'mApple2_mNeon.N20.fasta.txt

That means it is not able to create the gRNA fasta file for some reason. Any ideas?

[mApple_mNeon.txt](https://github.com/zhangchonglab/CRISPRi-functional-genomics-in-prokaryotes/files/3714571/mApple_mNeon.txt)

**Comment by batflorez** [comment]
Never mind I fixed, I have to avoid using underscores on file names.
